# Generated by Django 5.1.1 on 2024-09-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_2.player')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_2.prize')),
            ],
        ),
    ]
